### ISSUE TITLE
Compatibility with Anyio 4?

### ISSUE THREAD

**Issue by mm-andritz** [agronholm/redis-anyio#14]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

I see in the pyproject.toml that you are not compatible with anyio 4, but is it true? https://anyio.readthedocs.io/en/stable/migration.html seems to indicate that the only problem arises if you use the old Anyio ExceptionGroup but I don't see it in your code.

### Use case

I would like to install the library in a project where I already switched to Anyio 4. Thanks.

**Comment by agronholm** [comment]
I've updated the version pin. Given that this is an unreleased project, I don't plan to support AnyIO 3 in this project going forward.
